### PR TITLE
set rotate range in (-pi, pi]

### PR DESCRIPTION
**Pull request by linteck**
Set Rotate Angle in range of (-pi, pi].

### CODE REVIEW

**Comment by harbdog** [comment]
@linteck thanks can you please describe what this is aiming to fix or make better? An example or scenario would be ok too.

**Comment by linteck** [comment]
@harbdog Just feel that this part is wrong. It will change the angle A to an angle of 2PI - A.  It should only be A +/- 2*n*PI . For example (3+1/4) PI will be (-1-1/4)PI. The angle after calculation is not point to same direction as before.
```
if g.player.Angle >= pi2 {
		g.player.Angle = pi2 - g.player.Angle
	} else if
```

**Comment by harbdog** [comment]
Seems to work fine and simplifies expected angle, though technically the camera converts them just fine when outside of pi, -pi.

**Comment by linteck** [comment]
@harbdog "Raycaster-go" is a very good project. I like it very much. Thanks for your wonderful work. Just because I like the Reactor Pattern. Based on  "raycaster-go-demo", I have restructured it into a Reactor model.  After restructure the model, I added "harm effect" when projector hit sprite. And added audio effect. Here is the link of the project https://github.com/linteck/rego. Because it have changed too much code, I don't know if I should create a pull request for that.

**Pull request merged**
